application/kittens/views.py
# application/kittens/views.py 
from flask import Blueprint,render_template,redirect,url_for
from application import db 
from application.kittens.forms import AddForm,DelForm 
from application.models import Kitten 

kittens_blueprint = Blueprint('kittens',__name__,
                                template_folder='templates/kittens')

@kittens_blueprint.route('/add', methods=['GET','POST'])
def add_kit():

    form = AddForm()

    if form.validate_on_submit():

        name = form.name.data 

        new_kitten = Kitten(name)
        db.session.add(new_kitten)
        db.session.commit()

        return redirect(url_for('kittens.list'))
    return render_template('add.html', form=form)

@kittens_blueprint.route('/list')
def list():
    
    kittens = Kitten.query.all()

    return render_template('list.html', kittens=kittens)

@kittens_blueprint.route('/delete', methods=['GET','POST'])
def del_kit():

    form = DelForm()

    if form.validate_on_submit():
        id = form.id.data 
        kitten = Kitten.query.get(id)

        db.session.delete(kitten)
        db.session.commit()

        return redirect(url_for('kittens.list'))
    return render_template('delete.html',form=form)

application/owners/views.py
# application/owners/views.py
from flask import Blueprint,render_template,redirect,url_for
from application import db 
from application.models import Owner 
from application.owners.forms import AddForm 

owners_blueprint = Blueprint('owners',__name__,
                                template_folder='templates/owners')

@owners_blueprint.route('/add',methods=['GET','POST'])
def add():

    form = AddForm()
        
    if form.validate_on_submit():
        name = form.name.data 
        kit_id = form.kit_id.data 

        new_owner = Owner(name, kit_id)
        db.session.add(new_owner)
        db.session.commit()    

        return redirect(url_for('kittens.list'))
    
    return render_template('add_owner.html',form=form)

application/users/views.py
# applications/users/views.py 
from flask import Blueprint,render_template,redirect,url_for,flash,abort,request
from application import app,db,mail 
from application.token import generate_confirmation_token,confirm_token
from flask_login import login_user,login_required,logout_user
from application.models import User 
from application.users.forms import LoginForm,RegistrationForm
from flask_mail import Message
import datetime 

users_blueprint = Blueprint('users',__name__,
                                template_folder='templates/users')

def send_email_confirmation(to, html):
    msg = Message("Confirm Your Email",sender="glinkscraper@gmail.com",
                        recipients=[to], html=html)
    mail.send(msg)
        
@users_blueprint.route('/list',methods=['GET','POST'])
@login_required
def list():
    pass 

@users_blueprint.route('/init')
def init():
    db.create_all()
    return 'Done'

@users_blueprint.route('/send_mail')
def send_mail():
    try:
        msg = Message("Send Mail Tutorial!",sender="glinkscraper@gmail.com",recipients=["kanor.mang22@gmail.com"])
        msg.body = "Yo!\nGAGO"
        #msg.html = render_template('send_mail.html')
        mail.send(msg)

        return 'Mail sent!'
    except Exception as e:
        
        return(str(e)) 

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You logged out!')
    return redirect(url_for('kittens.list'))

@users_blueprint.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Logged in Successfully!')

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('kittens.list')
            
            return redirect(next)

    return render_template('login.html', form=form)

@users_blueprint.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        
        token = generate_confirmation_token(user.email)
        flash(f"token: {token}")
        confirm_url = url_for('users.confirm', token=token, _external=True)
        html = render_template('mail_send.html', confirm_url=confirm_url)
        send_email_confirmation('jpprjn@yahoo.com',html)
        login_user(user)
        #return redirect(url_for('users.login'))
    
        return redirect(url_for('kittens.list'))

    return render_template('register.html',form=form)

@users_blueprint.route('/confirm/<token>')
def confirm(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired')

    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login')
    else:
        user.confirmed = True 
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!')

    return redirect(url_for('index'))

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Username Check</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
            <a href="{{ url_for('index')}}" class="navbar-item nav-link">Home</a>
            <a href="{{ url_for('kittens.add_kit')}}" class="navbar-item nav-link">Add Kitten</a>
            <a href="{{ url_for('kittens.del_kit')}}" class="navbar-item nav-link">Remove Kitten</a>
            <a href="{{ url_for('kittens.list')}}" class="navbar-item nav-link">List of Kittens</a>
            <a href="{{ url_for('owners.add')}}" class="navbar-item nav-link">Add Owner</a>
            {% if current_user.is_authenticated %}
            <p>{{current_user.username}}</p>
                <a href="{{ url_for('users.logout')}}" class="navbar-item nav-link">Logout</a>
            {% else %}
                <a href="{{ url_for('users.login')}}" class="navbar-item nav-link">Login</a>
                <a href="{{ url_for('users.register')}}" class="navbar-item nav-link">Register</a>
            {% endif %}
            <a href="{{ url_for('users.init')}}" class="navbar-item nav-link">Create DB</a>
            <a class="navbar-item nav-link" href="{{ url_for('users.send_mail') }}">Send Mail</a>

        </div>
    </nav>    
    <div class="container">
        {% for mess in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <button type="button" class="fade close" data-dismiss='alert' arit-label='Close'>
                    <span aria-hidden="true">&times;</span>
                </button>
                {{mess}}
            </div>
        {% endfor %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

application/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <h1>Welcome to Kitten Adoptation</h1>
    </div>
{% endblock %}

application/templates/mail_send.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

application/templates/welcome.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <h1>email: {{email}}</h1>
    </div>
{% endblock %}